### ISSUE TITLE
[solved] Couldn't get it to work

### ISSUE THREAD

**Issue by ffigiel** [eeue56/elm-run#1]
I couldn't get the example to work - it would hang on `Runnig elm-make Main.elm (...)`. After running `elm-package install` and installing the deps everything worked

**Comment by ffigiel** [comment]
Perhaps `elm-make --yes` should be run instead? Or, assuming this was causing the problem, forward the prompt to the user.

**Comment by eeue56** [comment]
@megapctr want to make a PR for that?
